# Site settings
author: Bryce Dumas
title: 
header-img: img/home-bg.png
email: bryce.dumas@gmail.com
copyright_name: Bryce Dumas
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Bryce-Du

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
